### ISSUE TITLE
Ability to store completed quests

### ISSUE THREAD

**Issue by IoT-Gardener** [IoT-Gardener/Claans2#1]
We need a table to store quests completed by claan members.

Fields:
- Quest Completion ID (PK)
- Date completed
- Points earned (by generating score based on reward)
- Active Quest ID (FK) (active quest is unique, quest is not)
- User ID (FK)
- Claan ID (FK)

Depends on:
- [x] #14

**Comment by whompratt** [comment]
Done in cbd207737f0878badd8b861e5093fce53fc3c414
